server:
  port: 8081

spring:
  servlet:
    multipart:
      max-file-size: -1 # 上传单个文件大小
      max-request-size: -1 # 总上传文件大小

  mvc:
    # URL响应地址（Springboot默认为/**)
    static-path-pattern: /**
  resources:
    # 静态文件地址
    static-locations: file:resources
